### ISSUE TITLE
Content-overflowing-horizontal-scroll-bar-showing-Not-responsive

### ISSUE THREAD

**Issue by Rickey07** [GDSC-adgitm/Resume-builder#17]
### 📝 Description

The content is overflowing which is impacting the user experience and horizontal scroll bar is coming.Check in the below attached screenshot. 

### 🖼️ Screenshots

![Screenshot 2022-10-07 211951](https://user-images.githubusercontent.com/59111961/194595577-0319dc4f-ea61-47d1-8b58-a1e6d1752410.png)

**Comment by Guneetsinghtuli** [comment]
Yes there seems to be an overflow on the page, You can start working on this issue

**Comment by Rickey07** [comment]
Hi @Guneetsinghtuli 

I've fixed the bug. Please check.
