### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by Guneetsinghtuli** [GDSC-adgitm/Resume-builder#2]
### 📝 Description

A landing page or the first user page should be developed with the following sections in it.

1. Title with Image
2. Description
3. Description
4. Contributors

### 📋 Additional Information

Feel free to create your own design first for a better developing experience.

**Comment by sanyayaa** [comment]
I want to work on this issue.
 Kindly assign it to me under Hactoberfest 2022.

**Comment by sanyayaa** [comment]
Landing Page would look something like this.

![img](https://user-images.githubusercontent.com/103187781/194128874-83f85003-afa1-4d51-9b09-4f7ae7900242.jpeg)

**Comment by Guneetsinghtuli** [comment]
Okay Looks good, You can start working on this issue, and feel free to comment if you face any doubt
