### ISSUE TITLE
📝 Documentation Improvement: Update contribute.md

### ISSUE THREAD

**Issue by BTANISHA11** [GDSC-adgitm/Resume-builder#6]
### 📝 Description

Add some sections in contribute.md:

1. How to make a pull request
2. How to create a new branch
3.  Rules to follow .
4. How to clone a repositry
Pls assign this issue to me @

**Comment by Guneetsinghtuli** [comment]
Okay, you can start working on this issue.

**Comment by BTANISHA11** [comment]
okk
